### PR TITLE
Group structure on automorphisms

### PR DESCRIPTION
**Pull request by PatrickMassot**
This is an exercise I did in Lean and category theory: endow the type of automorphisms of any object with the obvious group structure. I think it's pretty natural to have it in this file. And of course I'd love to learn how to do it better if I did it wrong.

### CODE REVIEW

**Comment by kim-em** [comment]
Sorry, @PatrickMassot, that this was neglected for so long. If you're interested, I eventually implemented this here:

https://github.com/semorrison/lean-category-theory/blob/master/src/categories/endomorphisms.lean

**Comment by PatrickMassot** [comment]
No problem. I was a nice exercise for me anyway. Now I'm really curious about your `obviously` tactic. Is it documented somewhere? Can it be used in other projects?

**Comment by kim-em** [comment]
I'm getting 'obviously' ready for use. The roadmap is roughly:

1. Send a PR of a small piece of my category theory library to mathlib,
with all the 'obviously' proofs replaced by what obviously actually did
underneath (but all marked as such).
2. Convince Mario et al. that they'd actually like to have the automation
which makes it possible to remove all those proofs!
3. Send a PR of obviously to mathlib
4. Send the rest of my category theory library, this time with all the
boring proofs handled by obviously.

(2. may be the hard step, I'm not really sure!)

best,
Scott

**Comment by kim-em** [comment]
The obviously tactic is available for use, it’s in the
https://github.com/semorrison/lean-tidy repository. If you add that with
leanpkg, and then import tidy.tidy, you should have access to “tidy” and
“obviously”. Here “obviously” is just “tidy” (which may be better to start
with), followed by an attempt solve equational goals using a sequence of
rewrites.

Unfortunately tidy has a bad interaction with typeclasses at the moment (`x
+ y` gets unfolded to `nat.add x y`), which I’d like to resolve before
advising “tidy” for general use.

**Pull request closed without merging**
